name: "Test"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
            - name: Hello world action step
              uses: moatazeldebsy/sauce-labs-app-automate-action@V1.0.1
              with:
               device_name: 'Google Pixel GoogleAPI Emulator,platformVersion=10.0'
               data_center: 'eu-central-1'
              env:
               SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
               SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}

            - name: build with dotnet
              run: dotnet build --configuration release
            - name: run Test
              run: dotnet test
              env:
                SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
