name: "Test"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1

            - name: build with dotnet
              run: dotnet build --configuration release
            - name: run Test
              run: dotnet test --filter TestCategory=Sanity
