name: "Test"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                tunnelIdentifier: github-action-tunnel

            - name: build with dotnet
              run: dotnet build --configuration release
            - name: run Test
              run: dotnet test
              env:
                SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
